### ISSUE TITLE
service charmbit: Call method returns "local service call failed: connection is shut down"

### ISSUE THREAD

**Issue by mever** [juju/gocharm#34]
When doing service.Call in a hook it may return:
```local service call failed: connection is shut down```

I assume ServeLocalRPC is used and functional in your service.

To reproduce, execute the following steps in a hook:
1. make sure the service is running before the hook is executed
2. execute service.Call, now service.rpcClient is nil (this call should succeed)
3. execute service.Restart, now the service is running with a new socket
4. execute service.Call the service.rpcClient is still connected with the old socket, which returns an error.

**Comment by rogpeppe** [comment]
I believe this was fixed by PR #49. Please verify and I'll close this issue.

**Comment by mever** [comment]
I have tried to reproduce the issue I've reported and am very certain it is solved with the latest version of gocharm.
