### ISSUE TITLE
create mysql like provider

### ISSUE THREAD

**Issue by vtolstov** [juju/gocharm#44]
I'm try to implement mysql like provider, but have problems:
```
r.RegisterRelation(charm.Relation{Name: "db", Interface: "db", Role: charm.RelationRole("provider")})
```
creates 
```
provides:
  db: mysql
```

but i need
```
provides:
  db:
    interface: mysql
```

**Comment by rogpeppe** [comment]
Both those forms are equivalent (the first is shorthand for the second).

Have you tried using the charm?

**Comment by rogpeppe** [comment]
I'll close the issue now, as I believe this is working as intended.
