### ISSUE TITLE
allow to run goupx to minimize resulted binaries

### ISSUE THREAD

**Issue by vtolstov** [juju/gocharm#47]
Please add flag to run some command after building charm binary, my use-case - run goupx to minimize binary size.

**Comment by rogpeppe** [comment]
My plan is to do it slightly differently - compress the binary using gzip (or perhaps xz), then uncompress when necessary (determined by checking relative modification times in the hooks). This means that we'll get better compression, won't pay the decompression overhead each time a hook runs, and won't need to run the binary directly from the charm directory.
